# Generated by Django 6.0.5 on 2026-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='performance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
